apiVersion: apps/v1
kind: Deployment
metadata:
  name: sw-alert
  namespace: solar-wind
  labels:
    app: sw-alert
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sw-alert
  template:
    metadata:
      labels:
        app: sw-alert
    spec:
      containers:
      - name: alert
        image: sw-alert:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: MONGO_URI
          value: "mongodb://mongo-0.mongo:27017,mongo-1.mongo:27017,mongo-2.mongo:27017/?replicaSet=rs0"
        - name: MONGO_DB
          value: "spaceweather"
        - name: REDIS_URL
          value: 'redis://{{ include "redis.fullname" . }}.{{ .Values.namespace | default .Release.Namespace }}.svc.cluster.local:6379/0'
